#include "map.h"
#include "message.h"

#include <curses.h>

/*
    --- Client ---
*/

// Array of chars for each player to be rendered as
char map_players_char[MAX_PLAYERS] = {'a', 'b', 'c', 'd'};

// Game map to render
char map[MAP_HEIGHT][MAP_WIDTH] = {
    "########n#n########",
    "##x|  \\ O O /  (@)#",
    "## |              #",
    "## |             []",
    "## |             []",
    "## |             []",
    "#                []",
    "#                 #",
    "#(U)  /\"0\"0\"\\  (=)#",
    "########n#n########"
};

// Map with the attr of each char
int attr_map[MAP_HEIGHT][MAP_WIDTH] = {
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, A_UNDERLINE, A_BOLD, 0, 0, 0, A_UNDERLINE, A_UNDERLINE, A_UNDERLINE, A_UNDERLINE, A_UNDERLINE, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, A_UNDERLINE, A_BOLD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, A_UNDERLINE, A_BOLD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, A_UNDERLINE, A_BOLD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, A_UNDERLINE, A_BOLD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};
// Map with the color codes of each char
int color_map[MAP_HEIGHT][MAP_WIDTH] = {
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, NUMBER_COLOR_DEFAULT, MAP_COLOR_WALLS, NUMBER_COLOR_DEFAULT, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_TRASH, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, ITEM_COLOR_SALAD, MAP_COLOR_DEFAULT, MAP_COLOR_WALLS},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_WALLS},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_PLATES_1, MAP_COLOR_PLATES_1},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_PLATES_2, MAP_COLOR_PLATES_2},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_PLATES_1, MAP_COLOR_PLATES_1},
    {MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_PLATES_2, MAP_COLOR_PLATES_2},
    {MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_WALLS},
    {MAP_COLOR_WALLS, MAP_COLOR_DEFAULT, ITEM_COLOR_JUICE, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_OVEN, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, MAP_COLOR_DEFAULT, ITEM_COLOR_BREAD, MAP_COLOR_DEFAULT, MAP_COLOR_WALLS},
    {MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, NUMBER_COLOR_DEFAULT, MAP_COLOR_WALLS, NUMBER_COLOR_DEFAULT, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS, MAP_COLOR_WALLS},
};

/*
    --- Server ---
*/

// Game map with blocked spaces
int game_map[MAP_HEIGHT][MAP_WIDTH] = {
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1},
    {1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1},
    {1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1},
    {1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
};

// Game map with itens a player can get in each location
enum Item_type item_map[MAP_HEIGHT][MAP_WIDTH] = {
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, SALAD, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, JUICE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, BREAD, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
    {NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE},
};

// Game map with positions a player can use the trash
int trash_map[MAP_HEIGHT][MAP_WIDTH] = {
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

